created footer component
mendoza-allendg/sea-bit pull request #34
Opened 2024-01-21 00:09 UTC by vonnerbosa

## 🎟️ Issue
## 📝  Description

## 📷 Screenshots (if applicable)

## 📎 Checklist 

- [ ] Footer

## 😝 Out of scope 

## 📢 Additional Information

2024-01-22 00:02 UTC, mendoza-allendg requested changes
Nice PR! I've found some rooms for improvement, please check them! 🙇 

Overall, nice update!

Some bugs I found:
1. Footer dimensions are not aligned with header. Ultimately, we need to follow these dimensions in the app content with the exception of the SearchBar
![Screenshot 2024-01-21 153823](https://github.com/mendoza-allendg/sea-bit/assets/54106527/f9542119-9f0a-4bd9-a48e-bd0d8be6e3c4)

2. The footer's responsiveness can be improved
![Screenshot 2024-01-21 153916](https://github.com/mendoza-allendg/sea-bit/assets/54106527/0102728c-e79f-4225-896c-00a8f181b80f)

3. The footer is fixed in its position. We want the footer to only show at the bottom of the page (after all contents have been scrolled through)

https://github.com/mendoza-allendg/sea-bit/assets/54106527/8deb6e44-f693-4c25-9cf9-bd09bded6202

2024-01-22 00:02 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +          </ul>
This block has been repeated multiple times. It's better to create a list of contactMethods first, then loop them like this:

contactMethods.map((contact) => (
            < li className="list-none">
              < Link href={contact.link} color="foreground" className="text-xs">
                {contact.Name}
              < /Link>
            < /li >
))

2024-01-22 00:02 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +            </li>
Same here

2024-01-22 00:02 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +          </ul>
Same here.

2024-01-22 00:02 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +              <Image
Same here. Also, please put an alt prop in the image.

2024-01-22 00:02 UTC, mendoza-allendg commented on frontend/layouts/default.tsx
>        </footer>
You can add this inside the < Footer /> component

2024-01-23 07:40 UTC, vonnerbosa commented
Made improvements to the footer

2024-01-23 21:23 UTC, mendoza-allendg requested changes
Looking GOODDD!!
Just a few minor points then i think its all good to go! 💯

2024-01-23 21:23 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +const contactMethods = [
[nits]

If a variable is fixed, and wont change dynamically in the application and is outside the component scope, its better to use all caps like:

CONTACT_METHODS. However, I think that we might need the CONTACT_METHODS variable in the future for more important stuff, so its better to use something like COMPANY_CONTACT_METHODS

2024-01-23 21:23 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +const companyInfo = [
[nits]

array variables should be plural

2024-01-23 21:23 UTC, mendoza-allendg commented on frontend/components/shared/Footer.tsx
> +                {contactMethods.map((contact) => (
You don't have to manually put ids in the arrays. The .map() method provides the array's index and can be used as the key.

Try something like:
.map(contact, i) i is the index

2024-01-23 22:29 UTC, mendoza-allendg approved these changes
LGTM!
<img src="https://media2.giphy.com/media/cruO3FTeoAxjiTVxPW/giphy.gif"/>

2024-01-23 22:35 UTC, merged